import type {
  HemingDimensionDefinition,
  HemingMethodology,
  HemingRuleDefinition,
  RelationshipDefinition,
  RelationshipType,
} from './types';

export const HEMING_METHODOLOGY_VERSION = 'heming-method-v1';

const COMMON_DIMENSIONS: HemingDimensionDefinition[] = [
  {
    id: 'interaction_style',
    label: '互动与沟通方式',
    description: '比较双方表达、行动和面对外部环境时的节奏差异。',
    ownerAPalaces: ['命宫', '迁移宫', '福德宫'],
    ownerBPalaces: ['命宫', '迁移宫', '福德宫'],
    includeCurrentDaXian: false,
    includeAnnualTransit: false,
    requiredContextFields: ['observed_communication_pattern'],
  },
  {
    id: 'stage_timing',
    label: '阶段与时间同步',
    description: '比较双方当前大限及所选年份是否同时激活关系相关主题，不据此单独判断吉凶。',
    ownerAPalaces: ['命宫', '迁移宫', '福德宫'],
    ownerBPalaces: ['命宫', '迁移宫', '福德宫'],
    includeCurrentDaXian: true,
    includeAnnualTransit: true,
    requiredContextFields: ['relationship_stage'],
  },
];

const RELATIONSHIPS: RelationshipDefinition[] = [
  {
    type: 'romantic',
    label: '情侣与夫妻',
    description: '观察双方关系需求、亲密表达、现实协作和阶段性关系主题。',
    roles: [
      { owner: 'A', label: '甲方', description: '关系中的甲方，不预设性别角色。' },
      { owner: 'B', label: '乙方', description: '关系中的乙方，不预设性别角色。' },
    ],
    dimensions: [
      ...COMMON_DIMENSIONS,
      {
        id: 'relationship_needs',
        label: '关系需求与伴侣期待',
        description: '互参双方夫妻宫、命宫和福德宫，区分伴侣期待、个人特质与情绪需求。',
        ownerAPalaces: ['夫妻宫', '命宫', '福德宫'],
        ownerBPalaces: ['夫妻宫', '命宫', '福德宫'],
        includeCurrentDaXian: false,
        includeAnnualTransit: false,
        requiredContextFields: ['relationship_status', 'relationship_duration'],
      },
      {
        id: 'emotional_rhythm',
        label: '情绪与亲密节奏',
        description: '比较福德宫与命宫呈现的内在需求和外在表达，不把差异直接等同于不合。',
        ownerAPalaces: ['福德宫', '命宫'],
        ownerBPalaces: ['福德宫', '命宫'],
        includeCurrentDaXian: false,
        includeAnnualTransit: false,
        requiredContextFields: ['observed_emotional_needs'],
      },
      {
        id: 'practical_partnership',
        label: '现实生活协作',
        description: '观察双方对工作、资源、居住和生活安排的结构性偏好。',
        ownerAPalaces: ['官禄宫', '财帛宫', '田宅宫'],
        ownerBPalaces: ['官禄宫', '财帛宫', '田宅宫'],
        includeCurrentDaXian: true,
        includeAnnualTransit: false,
        requiredContextFields: ['living_arrangement', 'financial_arrangement'],
      },
    ],
    requiredRealityContext: ['relationship_status', 'relationship_duration', 'main_concern'],
  },
  {
    type: 'business',
    label: '商业合伙',
    description: '观察决策方式、职责分工、资源边界、风险承担和协作环境。',
    roles: [
      { owner: 'A', label: '合伙人甲', description: '合伙关系中的甲方。' },
      { owner: 'B', label: '合伙人乙', description: '合伙关系中的乙方。' },
    ],
    dimensions: [
      ...COMMON_DIMENSIONS,
      {
        id: 'role_allocation',
        label: '职责与决策分工',
        description: '比较命宫与官禄宫呈现的工作方式，用于设计职责而不是评定能力高低。',
        ownerAPalaces: ['命宫', '官禄宫'],
        ownerBPalaces: ['命宫', '官禄宫'],
        includeCurrentDaXian: true,
        includeAnnualTransit: false,
        requiredContextFields: ['planned_roles', 'decision_process'],
      },
      {
        id: 'financial_boundary',
        label: '资源与财务边界',
        description: '观察财帛、田宅与官禄结构，现实结论必须结合股权、预算和退出机制。',
        ownerAPalaces: ['财帛宫', '田宅宫', '官禄宫'],
        ownerBPalaces: ['财帛宫', '田宅宫', '官禄宫'],
        includeCurrentDaXian: true,
        includeAnnualTransit: false,
        requiredContextFields: ['equity_plan', 'budget_authority', 'exit_mechanism'],
      },
      {
        id: 'network_collaboration',
        label: '团队与外部协作',
        description: '比较交友宫和迁移宫所代表的团队、客户及外部环境互动方式。',
        ownerAPalaces: ['交友宫', '迁移宫'],
        ownerBPalaces: ['交友宫', '迁移宫'],
        includeCurrentDaXian: false,
        includeAnnualTransit: false,
        requiredContextFields: ['team_size', 'customer_type'],
      },
    ],
    requiredRealityContext: ['planned_roles', 'decision_process', 'equity_plan', 'exit_mechanism'],
  },
  {
    type: 'parent_child',
    label: '亲子关系',
    description: '观察照顾方式、权威边界、沟通节奏与成长阶段，不给儿童贴固定人格标签。',
    roles: [
      { owner: 'A', label: '父母方', description: '承担主要照顾或监护责任的一方。' },
      { owner: 'B', label: '子女方', description: '子女一方；未成年人结论必须采用成长性表达。' },
    ],
    dimensions: [
      ...COMMON_DIMENSIONS,
      {
        id: 'care_and_authority',
        label: '照顾与权威边界',
        description: '互参父母方子女宫、子女方父母宫及双方命宫。',
        ownerAPalaces: ['子女宫', '命宫', '福德宫'],
        ownerBPalaces: ['父母宫', '命宫', '福德宫'],
        includeCurrentDaXian: true,
        includeAnnualTransit: false,
        requiredContextFields: ['child_age', 'caregiving_arrangement'],
      },
      {
        id: 'growth_support',
        label: '成长支持方式',
        description: '比较学习、情绪和行动节奏，建议必须与实际年龄和发展阶段相匹配。',
        ownerAPalaces: ['福德宫', '官禄宫'],
        ownerBPalaces: ['福德宫', '命宫', '官禄宫'],
        includeCurrentDaXian: true,
        includeAnnualTransit: false,
        requiredContextFields: ['child_age', 'current_growth_challenge'],
      },
    ],
    requiredRealityContext: ['child_age', 'caregiving_arrangement', 'main_concern'],
  },
  {
    type: 'manager_report',
    label: '上下级关系',
    description: '观察管理、授权、反馈和职责边界，不能替代组织制度与绩效事实。',
    roles: [
      { owner: 'A', label: '管理者', description: '承担管理与授权责任的一方。' },
      { owner: 'B', label: '协作者', description: '承担具体职责并接受管理的一方。' },
    ],
    dimensions: [
      ...COMMON_DIMENSIONS,
      {
        id: 'management_style',
        label: '管理与反馈方式',
        description: '比较管理者官禄、交友与协作者命宫、官禄所呈现的工作互动方式。',
        ownerAPalaces: ['官禄宫', '交友宫', '命宫'],
        ownerBPalaces: ['命宫', '官禄宫', '福德宫'],
        includeCurrentDaXian: false,
        includeAnnualTransit: false,
        requiredContextFields: ['reporting_line', 'feedback_process'],
      },
      {
        id: 'responsibility_boundary',
        label: '职责与授权边界',
        description: '用于提示职责协商点，不依据命盘判断谁应获得职位或晋升。',
        ownerAPalaces: ['官禄宫', '财帛宫'],
        ownerBPalaces: ['官禄宫', '财帛宫'],
        includeCurrentDaXian: true,
        includeAnnualTransit: false,
        requiredContextFields: ['role_scope', 'decision_authority'],
      },
    ],
    requiredRealityContext: ['reporting_line', 'role_scope', 'main_concern'],
  },
  {
    type: 'friendship',
    label: '朋友关系',
    description: '观察相处节奏、信任边界、共同活动和资源往来。',
    roles: [
      { owner: 'A', label: '朋友甲', description: '朋友关系中的甲方。' },
      { owner: 'B', label: '朋友乙', description: '朋友关系中的乙方。' },
    ],
    dimensions: [
      ...COMMON_DIMENSIONS,
      {
        id: 'trust_boundary',
        label: '信任与边界',
        description: '比较交友宫、福德宫与命宫，不把单一煞曜直接解释为背叛。',
        ownerAPalaces: ['交友宫', '福德宫', '命宫'],
        ownerBPalaces: ['交友宫', '福德宫', '命宫'],
        includeCurrentDaXian: false,
        includeAnnualTransit: false,
        requiredContextFields: ['friendship_duration', 'resource_exchange'],
      },
      {
        id: 'shared_activity',
        label: '共同活动与支持',
        description: '观察迁移和官禄结构所呈现的外部活动与目标协作方式。',
        ownerAPalaces: ['迁移宫', '官禄宫'],
        ownerBPalaces: ['迁移宫', '官禄宫'],
        includeCurrentDaXian: false,
        includeAnnualTransit: false,
        requiredContextFields: ['shared_activities'],
      },
    ],
    requiredRealityContext: ['friendship_duration', 'main_concern'],
  },
  {
    type: 'custom',
    label: '其他关系',
    description: '使用通用互动与阶段维度，并要求用户明确双方角色和分析目标。',
    roles: [
      { owner: 'A', label: '甲方', description: '自定义关系中的甲方。' },
      { owner: 'B', label: '乙方', description: '自定义关系中的乙方。' },
    ],
    dimensions: COMMON_DIMENSIONS,
    requiredRealityContext: ['custom_relationship_label', 'owner_a_role', 'owner_b_role', 'main_concern'],
  },
];

const RULES: HemingRuleDefinition[] = [
  {
    id: 'romantic-mutual-partner-archetype',
    version: 1,
    name: '双方伴侣期待与命宫特质双向对应',
    relationshipTypes: ['romantic'],
    dimensionId: 'relationship_needs',
    priority: 80,
    confidence: 'medium',
    effect: 'observe',
    conditions: [
      { kind: 'star_overlap', left: { owner: 'A', palace: '夫妻宫' }, right: { owner: 'B', palace: '命宫' }, starTypes: ['major'], minCount: 1 },
      { kind: 'star_overlap', left: { owner: 'B', palace: '夫妻宫' }, right: { owner: 'A', palace: '命宫' }, starTypes: ['major'], minCount: 1 },
    ],
    evidenceOwners: ['A', 'B', 'interaction'],
    conclusionTemplate: '双方伴侣期待与对方命宫特质存在双向结构对应，属于值得结合现实相处验证的呼应。',
    adviceTemplate: '分别确认彼此真正重视的伴侣特质，避免把象征对应直接等同于现实适配。',
    source: { basis: 'project_methodology', references: ['M4-V1-6.2'], note: '对应性只表示观察重点，不直接计为吉或凶。' },
    conflictsWith: ['romantic-one-way-partner-archetype'],
    enabled: true,
  },
  {
    id: 'romantic-one-way-partner-archetype',
    version: 1,
    name: '单向伴侣期待与对方命宫特质对应',
    relationshipTypes: ['romantic'],
    dimensionId: 'relationship_needs',
    priority: 60,
    confidence: 'medium',
    effect: 'observe',
    conditions: [
      { kind: 'star_overlap', left: { owner: 'A', palace: '夫妻宫' }, right: { owner: 'B', palace: '命宫' }, starTypes: ['major'], minCount: 1 },
    ],
    evidenceOwners: ['A', 'B', 'interaction'],
    conclusionTemplate: '甲方伴侣期待与乙方命宫特质出现单向对应，需要进一步观察乙方的关系需求是否也能被回应。',
    adviceTemplate: '将双方需求分别表达，不把一方的熟悉感误当成双向共识。',
    source: { basis: 'project_methodology', references: ['M4-V1-6.2'] },
    conflictsWith: ['romantic-mutual-partner-archetype'],
    enabled: true,
  },
  {
    id: 'romantic-dual-emotional-pressure',
    version: 1,
    name: '双方内在压力信号同时偏多',
    relationshipTypes: ['romantic'],
    dimensionId: 'emotional_rhythm',
    priority: 70,
    confidence: 'medium',
    effect: 'challenging',
    conditions: [
      { kind: 'star_category_count', target: { owner: 'A', palace: '福德宫' }, category: 'sha', operator: 'gte', value: 2 },
      { kind: 'star_category_count', target: { owner: 'B', palace: '福德宫' }, category: 'sha', operator: 'gte', value: 2 },
    ],
    evidenceOwners: ['A', 'B', 'interaction'],
    conclusionTemplate: '双方福德宫同时出现较多传统压力信号，关系在高压阶段可能更需要主动调节情绪与沟通节奏。',
    adviceTemplate: '优先建立暂停争执、恢复情绪和再次沟通的现实机制；命盘信号不能替代心理或医疗专业支持。',
    source: { basis: 'traditional_interpretation', references: ['M4-V1-6.3'], note: '只表达压力观察，不推导分离、伤害或疾病。' },
    conflictsWith: [],
    enabled: true,
  },
  {
    id: 'business-similar-career-style',
    version: 1,
    name: '双方事业主星结构相似',
    relationshipTypes: ['business'],
    dimensionId: 'role_allocation',
    priority: 50,
    confidence: 'medium',
    effect: 'mixed',
    conditions: [
      { kind: 'star_overlap', left: { owner: 'A', palace: '官禄宫' }, right: { owner: 'B', palace: '官禄宫' }, starTypes: ['major'], minCount: 1 },
    ],
    evidenceOwners: ['A', 'B', 'interaction'],
    conclusionTemplate: '双方事业表达方式存在相似结构，可能形成默契，也可能造成职责重叠。',
    adviceTemplate: '用书面职责、决策权限和冲突处理机制验证相似性究竟形成协同还是竞争。',
    source: { basis: 'project_methodology', references: ['M4-V1-6.4'] },
    conflictsWith: [],
    enabled: true,
  },
  {
    id: 'manager-similar-career-style',
    version: 1,
    name: '上下级事业表达结构相似',
    relationshipTypes: ['manager_report'],
    dimensionId: 'responsibility_boundary',
    priority: 50,
    confidence: 'medium',
    effect: 'mixed',
    conditions: [
      { kind: 'star_overlap', left: { owner: 'A', palace: '官禄宫' }, right: { owner: 'B', palace: '官禄宫' }, starTypes: ['major'], minCount: 1 },
    ],
    evidenceOwners: ['A', 'B', 'interaction'],
    conclusionTemplate: '管理者与协作者的事业表达方式存在相似结构，可能便于形成共同语言，也可能使授权边界模糊。',
    adviceTemplate: '通过职责范围、最终决策权和反馈周期明确上下级边界，不用命盘结构替代绩效事实。',
    source: { basis: 'project_methodology', references: ['M4-V1-6.4'] },
    conflictsWith: [],
    enabled: true,
  },
  {
    id: 'shared-stage-relationship-focus',
    version: 1,
    name: '双方阶段主题同时聚焦关系相关宫位',
    relationshipTypes: ['romantic', 'business', 'parent_child', 'manager_report', 'friendship', 'custom'],
    dimensionId: 'stage_timing',
    priority: 40,
    confidence: 'medium',
    effect: 'observe',
    conditions: [
      { kind: 'stage_focus_in', owner: 'A', palaces: ['夫妻宫', '交友宫', '官禄宫', '子女宫', '父母宫'] },
      { kind: 'stage_focus_in', owner: 'B', palaces: ['夫妻宫', '交友宫', '官禄宫', '子女宫', '父母宫'] },
    ],
    evidenceOwners: ['A', 'B', 'interaction'],
    conclusionTemplate: '双方当前阶段都在触发与该关系相关的生活主题，互动的重要性可能上升，但不单独代表结果好坏。',
    adviceTemplate: '结合实际事件、关系阶段和双方选择判断机会与压力，不依据时间同步作出重大决定。',
    source: { basis: 'project_methodology', references: ['M4-V1-6.5'] },
    conflictsWith: [],
    enabled: true,
  },
  {
    id: 'unknown-time-confidence-guard',
    version: 1,
    name: '出生时间不确定时降低结论置信度',
    relationshipTypes: ['romantic', 'business', 'parent_child', 'manager_report', 'friendship', 'custom'],
    dimensionId: 'interaction_style',
    priority: 100,
    confidence: 'high',
    effect: 'insufficient',
    conditions: [
      { kind: 'birth_time_known', owner: 'A', expected: false },
    ],
    evidenceOwners: ['A'],
    conclusionTemplate: '甲方出生时间未确认，涉及命宫、身宫及宫位映射的结论需要降低置信度。',
    adviceTemplate: '优先补充或校正出生时间；在此之前仅保留跨候选命盘都稳定出现的观察。',
    source: { basis: 'product_safety', references: ['M4-V1-5.4'] },
    conflictsWith: [],
    enabled: true,
  },
  {
    id: 'unknown-time-confidence-guard-b',
    version: 1,
    name: '乙方出生时间不确定时降低结论置信度',
    relationshipTypes: ['romantic', 'business', 'parent_child', 'manager_report', 'friendship', 'custom'],
    dimensionId: 'interaction_style',
    priority: 100,
    confidence: 'high',
    effect: 'insufficient',
    conditions: [
      { kind: 'birth_time_known', owner: 'B', expected: false },
    ],
    evidenceOwners: ['B'],
    conclusionTemplate: '乙方出生时间未确认，涉及命宫、身宫及宫位映射的结论需要降低置信度。',
    adviceTemplate: '优先补充或校正出生时间；在此之前仅保留跨候选命盘都稳定出现的观察。',
    source: { basis: 'product_safety', references: ['M4-V1-5.4'] },
    conflictsWith: [],
    enabled: true,
  },
];

export const HEMING_METHODOLOGY: HemingMethodology = {
  version: HEMING_METHODOLOGY_VERSION,
  schoolPolicy: {
    id: 'sanhe-project-policy',
    version: 1,
    label: '项目三合派统一口径',
    allowedFacts: [
      'natal_chart',
      'twelve_palaces',
      'natal_stars',
      'natal_sihua_fixed',
      'brightness',
      'san_fang_si_zheng',
      'opposite_palace',
      'empty_palace_borrowing',
      'current_daxian_palace',
      'annual_transit_snapshot',
      'user_confirmed_context',
    ],
    forbiddenFacts: [
      'palace_self_sihua',
      'cross_chart_flying_sihua',
      'origin_palace',
      'model_invented_chart_fact',
      'single_global_compatibility_score',
      'unconfirmed_reality_as_fact',
    ],
    principles: [
      '甲乙两张命盘永远保持身份隔离。',
      '程序计算命盘事实，规则引擎生成结构化观察，AI 只负责解释。',
      '结构对应不自动等于吉，结构差异不自动等于凶。',
      '本命关系基线与大限流年阶段必须分层表达。',
      '现实关系信息只有经用户确认后才能作为事实进入结论。',
      '不输出单一总分，不替用户作出婚姻、合作、医疗或财务决定。',
    ],
  },
  relationships: RELATIONSHIPS,
  rules: RULES,
  resultLevels: {
    supportive: { label: '支持性', description: '存在可利用的协同结构，仍需现实验证。' },
    mixed: { label: '双向影响', description: '同一结构可能同时带来优势和摩擦。' },
    challenging: { label: '需要经营', description: '存在需要主动管理的压力或边界问题。' },
    observe: { label: '重点观察', description: '发现结构对应，但不足以判断正负结果。' },
    insufficient: { label: '信息不足', description: '关键出生或现实信息不足，结论需要降级。' },
  },
  prohibitedPhrases: [
    '天生不合',
    '必须分手',
    '必须离婚',
    '一定会离婚',
    '注定离婚',
    '必然背叛',
    '克夫',
    '克妻',
    '生离死别',
    '天作之合',
    '百分百匹配',
    '绝对适合创业',
    '一定能发财',
  ],
};

export function getRelationshipDefinition(type: RelationshipType): RelationshipDefinition {
  const definition = HEMING_METHODOLOGY.relationships.find(item => item.type === type);
  if (!definition) throw new Error(`未知关系类型：${type}`);
  return definition;
}
