import assert from 'node:assert/strict';
import { describeReportEvidence, reportScopeLines, evidenceSourceLabel } from '../lib/reports/evidence-presentation';
import type { ReportEvidenceDraft } from '../lib/reports/types';
const event: ReportEvidenceDraft = {evidenceKey:'event:demo',kind:'confirmed_event',label:'合成事件',source:'user_confirmed',facts:{datePrecision:'range',startDate:'2024-03-01',endDate:'2025-06-20',description:'合成说明'}};
assert.match(describeReportEvidence(event),/2024-03-01 至 2025-06-20（日期区间）/);
assert.match(describeReportEvidence({...event,facts:{datePrecision:'unknown',startDate:''}}),/时间未知/);
assert.match(describeReportEvidence({...event,facts:{datePrecision:'month',startDate:'2024-03'}}),/仅知月份/);
assert.doesNotMatch(describeReportEvidence({...event,facts:{datePrecision:'month',startDate:'2024-03'}}),/2024-03-01/);
assert.match(describeReportEvidence({...event,facts:{startDate:'2024',endDate:'2025'}}),/旧记录未标注精度/);
assert.equal(evidenceSourceLabel(event.source),'用户确认记录');
const palace: ReportEvidenceDraft = {evidenceKey:'palace:demo',kind:'palace',label:'宫位',source:'chart_snapshot',facts:{palace:'命宫',branch:'卯',stars:[{name:'天梁',siHua:'禄',brightness:'bright'}],isEmpty:true,borrowedStars:['太阳']}};
assert.match(describeReportEvidence(palace),/天梁·化禄·亮度较强/);
assert.match(describeReportEvidence(palace),/借对宫主星：太阳/);
assert.doesNotMatch(describeReportEvidence({...palace,facts:{stars:[null,{},12]}}),/undefined|\[object Object\]/);
const core: ReportEvidenceDraft = {evidenceKey:'chart:core',kind:'chart_core',label:'范围',source:'chart_snapshot',facts:{asOfDate:'2026-09-08',ageConvention:'农历虚岁，春节换岁',birthTimeConfidence:'unknown',eventSelection:{confirmedCount:25,matchedCount:0,selectedCount:0,omittedCount:25,truncatedCount:0,policy:'按专题分类筛选'}}};
const lines=reportScopeLines([core]).join('\n');
assert.match(lines,/选入 0 条/);assert.match(lines,/不代表没有发生/);assert.match(lines,/出生时辰未知/);assert.match(lines,/提供给模型参考/);
assert.match(reportScopeLines([]).join(''),/未保存完整分析范围/);
assert.match(reportScopeLines([{...core,facts:{}}]).join(''),/不会使用当前档案/);
assert.match(reportScopeLines([{...core,facts:{eventSelection:{}}}]).join(''),/未记录/);
console.log('报告依据展示测试通过：跨期日期、粗精度、旧版缺失、来源区分、四化借宫、范围数量与试排提示。');
